#!/usr/bin/env bash
#this is a program that displays fizzbuzz when the number 
#is a multiple of 3 and 5.
#displays fizz when the number is a multiple of 3
#displays buzz when the number is a multiple of 5
#and otherwise displays the number
#all in a list format
for i in {1..100}
do
if (( i % 3 == 0 && i % 5 == 0));
then
echo "FizzBuzz"
elif (( i % 3 == 0 ));
then
echo "Fizz"
elif (( i % 5 == 0 ));
then
echo "Buzz"
else
echo "$i"
fi
done
