#!/usr/bin/env bash
#this program tells the story of passwd
while IFS=: ead -r username password user_id group_id user_info home_dir shell;
do
echo "The user ${username} is part of the ${group_id} gang, lives in ${home_dir}
andrides ${shell}. ${user_id}'s place is protected by the passcode ${password}, 
more info about the user here: ${user_info}"
done < /etc/passwd
