#!/bin/bash
#this is a script that prints Best School ten times and on the 9th time it prints Best School followed by hi using a while loop
counter=0
while (( counter < 10 )); do
if (( counter == 8 )); then
	echo "Best School"
	echo "hi"
else
 echo "Best School"
fi 
((counter++))
done

