#!/usr/bin/env bash
#this is a script that prints numbers 1 - 20 and on the 4th, 9th, and 17th, it says "bad luck from ___" 
counter-0
while (( counter < 20 )); do
	(( counter++ ))
case $counter in 
	4) echo "4"; echo "bad luck from China" ;;
	9) echo "9"; echo "bad luck from Japan" ;;
	17) echo "17"; echo "bad luck from Italy" ;;
	*) echo "$counter" ;;
esac
done
