#!/usr/bin/env bash
#this script lists the hours up to 12 and the minutes up to 59, effectively creating a clock
hours=0
minutes=1
while (( hours <= 12 )); do
	echo "Hour: $hours"
	minutes=1
	while (( minutes <= 59 )); do
		echo "$minutes"
		(( minutes++ ))
	done 
	(( hours++ )) 
done
