#!/bin/bash
#this is a program that displays
#the content in the currents directory
#in a list format
#where only part of the name after the 
#first dash is displayed

for file in *; do

if [[ $file == *_* ]];
then
echo "${file#*_}"
else
echo "#file"
fi
done
